# Generated by Django 5.0.1 on 2024-03-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_total_price_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pet',
            new_name='product',
        ),
    ]
